### PR TITLE
Changed restaurants from list style to carousel style with "test" image for review

### PR DESCRIPTION
**Pull request by Jaemarlee**
Changed restaurants from list style to carousel style with "test" image for review. If everyone is ok with this, I will continue to add reviews and hours of operation and update remaining cities with similar layouts.

### CODE REVIEW

**Comment by yjlmotley** [comment]
I like it. Are you hard coding the images in as well? It's a lot of effort. It does look better though. 

Another thought. If we end up using that styling, what do you think about doing 9 cards for asthetics and then keeping the height the same no matter the image size?

**Review by yjlmotley — APPROVED** [review]
nice start!

**Review by Legends-Land — COMMENTED** [review]
Lets go!

**Review by Legends-Land — APPROVED** [review]
Lets go!

**Pull request merged**
